CREATE DATABASE tmall;

USE tmall;

CREATE TABLE USER(
	
	id INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) DEFAULT NULL,
	PASSWORD VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(id)

)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE category(
	
	id INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE property(
	
	id INT(11) NOT NULL AUTO_INCREMENT,
	cid INT(11) DEFAULT NULL,
	NAME VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_property_category FOREIGN KEY(cid) REFERENCES category(id)

)

CREATE TABLE PRODUCT (
	id INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) DEFAULT NULL,
	subtitle VARCHAR(255) DEFAULT NULL,
	originalPrice FLOAT DEFAULT NULL,
	promotePrice FLOAT DEFAULT NULL,
	stock INT(11) DEFAULT NULL,
	cid INT(11) DEFAULT NULL,
	createDATE DATETIME DEFAULT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_product_category FOREIGN KEY(cid) REFERENCES category(id)

	
)

CREATE TABLE propertyvalue(
	id INT(11) NOT NULL AUTO_INCREMENT,
	pid INT(11) DEFAULT NULL,
	ptid INT(11) DEFAULT NULL,
	VALUE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(Id),
	CONSTRAINT fk_propertyvalue_property FOREIGN KEY(ptid) REFERENCES property(id),
	CONSTRAINT fk_propertyvalue_product FOREIGN KEY(pid) REFERENCES product(id)
)

CREATE TABLE productimage(
	id INT(11) NOT NULL AUTO_INCREMENT,
	pid INT(11) DEFAULT NULL,
	TYPE VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_productimage_product FOREIGN KEY(pid) REFERENCES product(id)

)

CREATE TABLE review(
	id INT(11) NOT NULL AUTO_INCREMENT,
	content VARCHAR(4000) DEFAULT NULL,
	uid INT(11) DEFAULT NULL,
	pid INT (11) DEFAULT NULL,
	createDate DATETIME DEFAULT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_review_product FOREIGN KEY(pid) REFERENCES product(id),
	CONSTRAINT fk_review_user FOREIGN KEY(uid) REFERENCES USER(id)

)

CREATE TABLE order_(
	id INT(11) NOT NULL AUTO_INCREMENT,
	orderCode VARCHAR(255) DEFAULT NULL,
	address VARCHAR(255) DEFAULT NULL,
	post VARCHAR(255)DEFAULT NULL,
	receiver VARCHAR (255) DEFAULT NULL,
	mobile VARCHAR(255) DEFAULT NULL,
	userMessage VARCHAR(255) DEFAULT NULL,
	createDate DATETIME DEFAULT NULL,
	payDate DATETIME DEFAULT NULL,
	confirmDate DATETIME DEFAULT NULL,
	uid INT(11) DEFAULT NULL,
	STATUS VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_order_user FOREIGN KEY(uid) REFERENCES USER(id)


)

CREATE TABLE orderitem(
	
	id INT(11) NOT NULL AUTO_INCREMENT,
	pid INT(11) DEFAULT NULL,
	oid INT(11) DEFAULT NULL,
	uid INT(11) DEFAULT NULL,
	number INT(11) DEFAULT NULL,
	PRIMARY KEY(id),
	CONSTRAINT fk_orderitem_user FOREIGN KEY(uid) REFERENCES USER(id),
	CONSTRAINT fk_orderitem_product FOREIGN KEY(pid) REFERENCES product(id)

)